name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: 'npm install'

      - name: Build step
        run: |
          touch .env
          echo VITE_API_URL=${{ secrets.API_URL }} >> .env
          echo VITE_API_TOKEN=${{ secrets.API_TOKEN }} >> .env
          npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'rss-mwc'
          entrypoint: 'https://deno.land/std@0.217.0/http/file_server.ts'
          root: 'dist'
